name: chapter_one_challenge

on: 
  push:
    branches:
      - main

jobs: 
  job1:
    name: Job 1
    runs-on: ubuntu-latest
    steps:
    - name: step1
      uses: actions/checkout@v2
    - name: step2
      run: date
    
  job2:
    name: Job 2
    runs-on: windows-latest
    steps:
    - name: step1
      uses: actions/checkout@v2
    - name : step2
      run:  Get-Date
    
  job3:
    name: Job 3
    runs-on: macos-latest
    steps:
    - name: step1
      uses: actions/checkout@v2
    - name : step2
      run: date
   
  job4:
    name: Job 4
    runs-on: ubuntu-latest
    steps:
    - name: step1
      uses: actions/checkout@v2
    - name : step2
      run: date
    needs: [job1, job2, job3]
  
