name : first

on: 
  push:
    branches: 
      - develop
      - master

jobs:

  job1:
    name : First Job
    runs-on: ubuntu-latest
    steps: 
    - name : Step One
      uses: actions/checkout@v2

    - name : Step two
      run: env | sort
      

  job2:
    name : Second Job
    needs: job1
    runs-on: windows-latest
    steps:
    - name : Step One
      uses: actions/checkout@v2 

    - name : Step two
      run: "Get-ChildItem Env: | Sort-Object Name"

