name: python syntax checker

on: 
  push:
    branches:
      - main

jobs:

  syntaxchecker:
    name: python_syntax_checking
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        
      - name: checksyntax
        uses: cclauss/Find-Python-syntax-errors-action@v0.2.0
          
      
    
